-- Supabase SQL schema for Nandini Pharma
create table if not exists user_data (
  id bigint generated by default as identity primary key,
  user_id uuid unique not null,
  email text,
  name text,
  phone text,
  address text,
  pincode text,
  landmark text,
  alt_phone text,
  city text,
  state text,
  created_at timestamp with time zone default now()
);

create table if not exists user_otp (
  id bigint generated by default as identity primary key,
  email text not null,
  channel text not null default 'email',
  sent_at timestamp with time zone default now()
);

create table if not exists user_cart (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint not null,
  packaging_type text not null,
  name text,
  price numeric,
  image text,
  quantity int not null default 1,
  updated_at timestamp with time zone default now(),
  unique(user_id, product_id, packaging_type)
);

create table if not exists user_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  order_id text unique not null,
  status text not null check (status in ('failed','processing','placed','delivered')),
  items jsonb not null,
  total text,
  shipping jsonb,
  created_at timestamp with time zone default now()
);

-- User addresses
create table if not exists user_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  label text, -- e.g., Home, Office
  name text,
  phone text,
  address text not null,
  city text not null,
  pincode text not null,
  is_default boolean not null default false,
  created_at timestamp with time zone default now()
);

alter table user_data enable row level security;
alter table user_otp enable row level security;
alter table user_cart enable row level security;
alter table user_orders enable row level security;
alter table user_addresses enable row level security;

create policy "user can view own profile" on user_data for select using (auth.uid() = user_id);
create policy "upsert own profile" on user_data for insert with check (auth.uid() = user_id);
create policy "upsert own profile update" on user_data for update using (auth.uid() = user_id);

create policy "log otp any" on user_otp for insert with check (true);

create policy "manage own cart" on user_cart for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "manage own orders" on user_orders for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
-- Serviceable Pincodes
create table if not exists pincode_status (
  id bigint generated by default as identity primary key,
  pincode text unique not null,
  state text,
  district text,
  status int not null default 1 -- 1 deliverable, 0 not deliverable
);


create policy "manage own addresses" on user_addresses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

